### ISSUE TITLE
Create a page for MOSFETs

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jlcsearch#10]
Make sure to use aider and sonnet to generate the derived table, see the steps in the README

There are currently no preview deployments for this repo, so take a screenshot or video to show off!

There will be bounties for more pages on this repo shortly!

/bounty $15

**Comment by Abse2001** [comment]
@seveibar how can I test this do I need an api key?
![Image](https://github.com/user-attachments/assets/7e0b7f5b-4f43-4c6c-bdaf-174ddbbafdd4)

![Image](https://github.com/user-attachments/assets/8228f838-d7dc-4113-99a9-d9799f94209e)
